version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

hooks:
  BeforeInstall:
    - location: BeforeInstall.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: AfterInstall.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: ApplicationStop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: ApplicationStart.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: ValidateService.sh
      timeout: 60
      runas: root